export const stories = [
  {
    id: 'hanh-trinh-van-gioi',
    title: 'Hành Trình Vạn Giới',
    author: 'Lê Minh',
    category: 'Tiên hiệp',
    description:
      'Một thiếu niên vô danh bỗng chạm phải bí mật cổ xưa, bắt đầu cuộc hành trình chinh phục vạn giới bằng ý chí và tu vi bất tận.',
    cover: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 30%, #f472b6 100%)',
    views: '1.2M',
    rating: 4.9,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Khởi đầu', duration: '12:14', isVip: false },
      { id: 2, title: 'Chương 2: Huyền cơ', duration: '11:48', isVip: false },
      { id: 3, title: 'Chương 3: Bí mật', duration: '14:02', isVip: true },
      { id: 4, title: 'Chương 4: Vách đá', duration: '13:40', isVip: false },
      { id: 5, title: 'Chương 5: Khai giới', duration: '15:20', isVip: true },
    ],
  },
  {
    id: 'thien-menh-chi-dao',
    title: 'Thiên Mệnh Chi Đạo',
    author: 'Bạch Trầm',
    category: 'Kiếm hiệp',
    description:
      'Đường kiếm của một thiếu niên nghèo được thiên mệnh chọn, dẫn dắt anh bước qua thăng trầm của võ lâm và số phận.',
    cover: 'linear-gradient(135deg, #16213e 0%, #1d4ed8 35%, #60a5fa 100%)',
    views: '980K',
    rating: 4.8,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Đường kiếm', duration: '10:54', isVip: false },
      { id: 2, title: 'Chương 2: Phong ba', duration: '13:30', isVip: false },
      { id: 3, title: 'Chương 3: Luyện kiếm', duration: '12:05', isVip: true },
      { id: 4, title: 'Chương 4: Hắc kiếm', duration: '11:28', isVip: false },
      { id: 5, title: 'Chương 5: Cầu hôn', duration: '14:18', isVip: true },
    ],
  },
  {
    id: 'kiem-vuc',
    title: 'Kiếm Vực',
    author: 'Phương Huy',
    category: 'Huyền huyễn',
    description:
      'Một nơi gọi là Kiếm Vực tụ đầy các đấu sĩ, nơi người mạnh sẽ định đoạt vận mệnh và những lời thề của thời đại.',
    cover: 'linear-gradient(135deg, #1f2937 0%, #0f766e 35%, #2dd4bf 100%)',
    views: '1.5M',
    rating: 4.7,
    isVip: false,
    status: 'Hoàn thành',
    episodes: [
      { id: 1, title: 'Chương 1: Đỉnh kiếm', duration: '11:23', isVip: false },
      { id: 2, title: 'Chương 2: Tử chiến', duration: '12:58', isVip: false },
      { id: 3, title: 'Chương 3: Cấm vực', duration: '15:10', isVip: true },
      { id: 4, title: 'Chương 4: Tàn đấu', duration: '13:45', isVip: false },
      { id: 5, title: 'Chương 5: Huyền kiếm', duration: '16:30', isVip: true },
    ],
  },
  {
    id: 'de-lo',
    title: 'Đế Lộ',
    author: 'Ngọc Vân',
    category: 'Tiên hiệp',
    description:
      'Con đường đế vương không ngừng mở ra, mỗi bước đi đều đòi hỏi một giá trị mà người kia rất dễ đánh mất.',
    cover: 'linear-gradient(135deg, #4b5563 0%, #9a5b00 35%, #fbbf24 100%)',
    views: '890K',
    rating: 4.6,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Tại đế', duration: '12:12', isVip: false },
      { id: 2, title: 'Chương 2: Tinh thạch', duration: '14:22', isVip: true },
      { id: 3, title: 'Chương 3: Tấn cấp', duration: '13:15', isVip: false },
      { id: 4, title: 'Chương 4: Lời thề', duration: '12:50', isVip: true },
      { id: 5, title: 'Chương 5: Đế cơ', duration: '15:05', isVip: false },
    ],
  },
  {
    id: 'van-co-than-thanh',
    title: 'Vạn Cổ Thần Thành',
    author: 'Dao Hàn',
    category: 'Fantasy',
    description:
      'Mảnh thành cổ từng lạc mất trong thời gian trở thành nơi tụ hội của những kẻ trăm năm sau tìm đến truyền thuyết.',
    cover: 'linear-gradient(135deg, #3b0764 0%, #a855f7 38%, #f9a8d4 100%)',
    views: '760K',
    rating: 4.9,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Thành cổ', duration: '11:40', isVip: false },
      { id: 2, title: 'Chương 2: Săn thần', duration: '13:02', isVip: false },
      { id: 3, title: 'Chương 3: Ẩn tích', duration: '12:35', isVip: true },
      { id: 4, title: 'Chương 4: Căn cứ', duration: '14:48', isVip: true },
      { id: 5, title: 'Chương 5: Khóa hầm', duration: '13:12', isVip: false },
    ],
  },
  {
    id: 'tinh-ha-dai-dao',
    title: 'Tinh Hà Đại Đạo',
    author: 'Kỳ Sóng',
    category: 'Cổ đại',
    description:
      'Bên trong đại đạo mênh mang, mỗi linh hồn đều mang một vận mệnh riêng và chiến trường của cả bầu trời.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #1e40af 40%, #a5b4fc 100%)',
    views: '1.1M',
    rating: 4.8,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Tinh hà', duration: '12:42', isVip: false },
      { id: 2, title: 'Chương 2: Thất bại', duration: '11:36', isVip: false },
      { id: 3, title: 'Chương 3: Đại đạo', duration: '15:04', isVip: true },
      { id: 4, title: 'Chương 4: Quyết tâm', duration: '13:41', isVip: false },
      { id: 5, title: 'Chương 5: Ranh giới', duration: '14:59', isVip: true },
    ],
  },
  {
    id: 'cuu-thien-kiem-chu',
    title: 'Cửu Thiên Kiếm Chủ',
    author: 'Hải Dương',
    category: 'Kiếm hiệp',
    description:
      'Trong cuộc tranh đoạt thiên kiếm cổ, kẻ thống trị không chỉ là người mạnh nhất mà là người chịu được mọi thử thách.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #334155 35%, #7dd3fc 100%)',
    views: '870K',
    rating: 4.7,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Cửu thiên', duration: '10:48', isVip: false },
      { id: 2, title: 'Chương 2: Thử kiếm', duration: '12:12', isVip: false },
      { id: 3, title: 'Chương 3: Thiên kiếm', duration: '13:26', isVip: false },
      { id: 4, title: 'Chương 4: Hộ pháp', duration: '14:09', isVip: true },
      { id: 5, title: 'Chương 5: Mưa đao', duration: '15:42', isVip: true },
    ],
  },
  {
    id: 'than-ma-chi-lo',
    title: 'Thần Ma Chi Lộ',
    author: 'Mộc Tinh',
    category: 'Huyền huyễn',
    description:
      'Khi ma đạo quật khởi và thần tộc cũ lật mặt, mỗi người đều phải chọn giữa sinh tử và danh vọng.',
    cover: 'linear-gradient(135deg, #581c87 0%, #8b5cf6 35%, #f0abfc 100%)',
    views: '1.9M',
    rating: 4.9,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Tĩnh lạc', duration: '11:07', isVip: false },
      { id: 2, title: 'Chương 2: Nửa đường', duration: '12:19', isVip: false },
      { id: 3, title: 'Chương 3: Chết đi', duration: '14:58', isVip: true },
      { id: 4, title: 'Chương 4: Sứ mạng', duration: '13:33', isVip: true },
      { id: 5, title: 'Chương 5: Ma đường', duration: '15:15', isVip: true },
    ],
  },
  {
    id: 'luan-hoi-chi-mon',
    title: 'Luân Hồi Chi Môn',
    author: 'Huy Vũ',
    category: 'Ngôn tình',
    description:
      'Tình yêu và niềm tin được đặt trong vòng luân hồi, nơi mỗi người đi qua một cuộc tái sinh để gặp nhau lại.',
    cover: 'linear-gradient(135deg, #7c2d12 0%, #f97316 40%, #fdba74 100%)',
    views: '720K',
    rating: 4.5,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Cửa luân hồi', duration: '11:40', isVip: false },
      { id: 2, title: 'Chương 2: Giao thoa', duration: '13:54', isVip: false },
      { id: 3, title: 'Chương 3: Hồi ức', duration: '12:18', isVip: true },
      { id: 4, title: 'Chương 4: Tái sinh', duration: '14:44', isVip: false },
      { id: 5, title: 'Chương 5: Mệnh lệnh', duration: '15:01', isVip: true },
    ],
  },
  {
    id: 'van-gioi-tien-tong',
    title: 'Vạn Giới Tiên Tông',
    author: 'Đan Mộc',
    category: 'Tiên hiệp',
    description:
      'Bí mật của một vị tiền tông bị phong ấn đã làm rung chuyển từng thế giới trong vạn giới.',
    cover: 'linear-gradient(135deg, #111827 0%, #1d4ed8 40%, #c4b5fd 100%)',
    views: '1.3M',
    rating: 4.8,
    isVip: true,
    status: 'Hoàn thành',
    episodes: [
      { id: 1, title: 'Chương 1: Phong ấn', duration: '12:38', isVip: false },
      { id: 2, title: 'Chương 2: Tế đan', duration: '13:10', isVip: false },
      { id: 3, title: 'Chương 3: Tiên nguyên', duration: '15:12', isVip: true },
      { id: 4, title: 'Chương 4: Trận chiến', duration: '14:35', isVip: true },
      { id: 5, title: 'Chương 5: Tự do', duration: '16:02', isVip: true },
    ],
  },
  {
    id: 'cau-vang-cua-troi',
    title: 'Cầu Vàng Của Trời',
    author: 'Tâm Khiết',
    category: 'Thần thoại',
    description:
      'Một trăm năm sau, con đường thần thoại cũ lại bắt đầu hé lộ những bí mật chưa từng ai biết đến.',
    cover: 'linear-gradient(135deg, #1f2937 0%, #6d28d9 35%, #facc15 100%)',
    views: '540K',
    rating: 4.4,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Huyền thoại', duration: '11:22', isVip: false },
      { id: 2, title: 'Chương 2: Giếng vàng', duration: '13:09', isVip: true },
      { id: 3, title: 'Chương 3: Sợi xích', duration: '12:44', isVip: false },
      { id: 4, title: 'Chương 4: Đêm mưa', duration: '14:18', isVip: false },
      { id: 5, title: 'Chương 5: Thần đường', duration: '15:12', isVip: true },
    ],
  },
  {
    id: 'song-than-khu-rung',
    title: 'Sông Thần Khu Rừng',
    author: 'Xin Thinh',
    category: 'Fantasy',
    description:
      'Trong khu rừng thần bí, người trẻ phải bình sinh ở giữa những sinh vật quỷ dị và những lời nguyền của thiên nhiên.',
    cover: 'linear-gradient(135deg, #14532d 0%, #22c55e 35%, #bbf7d0 100%)',
    views: '505K',
    rating: 4.6,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Khu rừng', duration: '11:05', isVip: false },
      { id: 2, title: 'Chương 2: Gió độc', duration: '13:12', isVip: false },
      { id: 3, title: 'Chương 3: Bạch hổ', duration: '12:20', isVip: false },
      { id: 4, title: 'Chương 4: Mật lộ', duration: '15:05', isVip: true },
      { id: 5, title: 'Chương 5: Hồn núi', duration: '14:33', isVip: true },
    ],
  },
  {
    id: 'lang-nguoi-phan-hoa',
    title: 'Làng Người Phản Hóa',
    author: 'Thiên Tâm',
    category: 'Kinh dị',
    description:
      'Một ngôi làng bất ngờ biến đổi và thắp lên những nguyền rủa không ai muốn nhắc đến, buộc người ta phải đối mặt với quá khứ.',
    cover: 'linear-gradient(135deg, #111827 0%, #374151 35%, #a78bfa 100%)',
    views: '640K',
    rating: 4.5,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Phản hóa', duration: '12:55', isVip: true },
      { id: 2, title: 'Chương 2: Bóng đêm', duration: '14:12', isVip: false },
      { id: 3, title: 'Chương 3: Dòng máu', duration: '13:48', isVip: true },
      { id: 4, title: 'Chương 4: Cửa mộ', duration: '15:30', isVip: false },
      { id: 5, title: 'Chương 5: Tử hồn', duration: '16:04', isVip: true },
    ],
  },
  {
    id: 'tu-kiem-giang-ho',
    title: 'Tử Kiếm Giang Hồ',
    author: 'Vũ Thần',
    category: 'Kiếm hiệp',
    description:
      'Một kiếm khách cố gắng bước ra khỏi lịch sử, nhưng giang hồ đã đặt tên cho anh trên sông máu lửa.',
    cover: 'linear-gradient(135deg, #1e293b 0%, #4f46e5 30%, #c4b5fd 100%)',
    views: '620K',
    rating: 4.7,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Cỏ đen', duration: '10:23', isVip: false },
      { id: 2, title: 'Chương 2: Mưa kiếm', duration: '13:05', isVip: false },
      { id: 3, title: 'Chương 3: Bản đồ', duration: '12:50', isVip: true },
      { id: 4, title: 'Chương 4: Kẻ thù', duration: '16:12', isVip: true },
      { id: 5, title: 'Chương 5: Chết lại', duration: '14:34', isVip: false },
    ],
  },
  {
    id: 'nang-tho-sex',
    title: 'Nàng Thơ Sẽ Xinh',
    author: 'Mộc Mai',
    category: 'Ngôn tình',
    description:
      'Một nữ chính khởi đầu từ một cuộc sống nhỏ bé, rồi dần chạm tới những cảm xúc lớn hơn cả giấc mơ.',
    cover: 'linear-gradient(135deg, #831843 0%, #ec4899 38%, #fbcfe8 100%)',
    views: '595K',
    rating: 4.6,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Vết nứt', duration: '12:31', isVip: false },
      { id: 2, title: 'Chương 2: Chợt thấy', duration: '11:28', isVip: true },
      { id: 3, title: 'Chương 3: Từ từ', duration: '13:18', isVip: false },
      { id: 4, title: 'Chương 4: Tự tin', duration: '14:58', isVip: true },
      { id: 5, title: 'Chương 5: Gặp lại', duration: '12:10', isVip: false },
    ],
  },
  {
    id: 'thanh-kiem-tren-may',
    title: 'Thành Kiếm Trên Mây',
    author: 'An Nhiên',
    category: 'Đô thị',
    description:
      'Giữa thành phố và mây trời, những người thừa nhận mình đã mất đi đến mức nào mới có thể tìm lại điều mà họ cần.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #2563eb 35%, #67e8f9 100%)',
    views: '467K',
    rating: 4.3,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Mùa mưa', duration: '13:06', isVip: false },
      { id: 2, title: 'Chương 2: Giao thoa', duration: '12:24', isVip: false },
      { id: 3, title: 'Chương 3: Đèn thành', duration: '14:11', isVip: false },
      { id: 4, title: 'Chương 4: Trên mây', duration: '15:48', isVip: true },
      { id: 5, title: 'Chương 5: Chân trời', duration: '12:58', isVip: true },
    ],
  },
  {
    id: 'vong-du-ky-bien',
    title: 'Võng Du Kỳ Biến',
    author: 'Lương Nam',
    category: 'Võng du',
    description:
      'Một giấc mơ không điển hình kéo người trẻ vào thế giới mới, nơi mỗi bước đi đều có thể khiến họ mất hết ký ức.',
    cover: 'linear-gradient(135deg, #3b0764 0%, #a21caf 35%, #e879f9 100%)',
    views: '712K',
    rating: 4.8,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Mơ ngủ', duration: '10:59', isVip: false },
      { id: 2, title: 'Chương 2: Cửa lạ', duration: '12:48', isVip: false },
      { id: 3, title: 'Chương 3: Mất kiểm soát', duration: '15:16', isVip: true },
      { id: 4, title: 'Chương 4: Trải nghiệm', duration: '13:31', isVip: true },
      { id: 5, title: 'Chương 5: Nửa giấc', duration: '14:38', isVip: true },
    ],
  },
  {
    id: 'dai-loi-thanh-pha',
    title: 'Đại Lôi Thành Phá',
    author: 'Hào Tinh',
    category: 'Xuyên không',
    description:
      'Khi thời không bị xé rách, vài người phải làm ngược lại thứ mà họ từng tin là định mệnh.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #7c3aed 35%, #f9a8d4 100%)',
    views: '664K',
    rating: 4.7,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Gãy thời', duration: '11:08', isVip: false },
      { id: 2, title: 'Chương 2: Lôi phách', duration: '12:44', isVip: false },
      { id: 3, title: 'Chương 3: Cửa không', duration: '15:10', isVip: true },
      { id: 4, title: 'Chương 4: Nỗi buồn', duration: '14:21', isVip: false },
      { id: 5, title: 'Chương 5: Xuyên qua', duration: '15:38', isVip: true },
    ],
  },
  {
    id: 'huyen-thu-van-giang',
    title: 'Huyền Thủ Vạn Giang',
    author: 'Thiên Dương',
    category: 'Lịch sử',
    description:
      'Một vương triều chìm trong mưa sương, nơi những người làm chủ quân pháp phải đánh bại cả thời đại.',
    cover: 'linear-gradient(135deg, #1d4ed8 0%, #0ea5e9 40%, #dbeafe 100%)',
    views: '500K',
    rating: 4.4,
    isVip: false,
    status: 'Hoàn thành',
    episodes: [
      { id: 1, title: 'Chương 1: Vạn giang', duration: '11:58', isVip: false },
      { id: 2, title: 'Chương 2: Tượng đá', duration: '12:35', isVip: false },
      { id: 3, title: 'Chương 3: Vương triều', duration: '13:42', isVip: true },
      { id: 4, title: 'Chương 4: Mộ dã', duration: '14:22', isVip: false },
      { id: 5, title: 'Chương 5: Kết cục', duration: '15:10', isVip: true },
    ],
  },
  {
    id: 'thien-luc-nguyen-thu',
    title: 'Thiên Lực Nguyên Thủ',
    author: 'Nguyên Tố',
    category: 'Trinh thám',
    description:
      'Một vụ án bị giấu trong đêm, một tay thám tử bất ngờ phát hiện mọi lời khai đều có thể nói dối.',
    cover: 'linear-gradient(135deg, #111827 0%, #7c2d12 35%, #fca5a5 100%)',
    views: '388K',
    rating: 4.1,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Dấu vết', duration: '11:20', isVip: false },
      { id: 2, title: 'Chương 2: Suy luận', duration: '12:16', isVip: false },
      { id: 3, title: 'Chương 3: Gần nhau', duration: '13:24', isVip: true },
      { id: 4, title: 'Chương 4: Giấu mặt', duration: '15:31', isVip: true },
      { id: 5, title: 'Chương 5: Bên ngoài', duration: '14:45', isVip: false },
    ],
  },
  {
    id: 'long-dong-bien-tien',
    title: 'Long Động Biến Tiền',
    author: 'Duy Hòa',
    category: 'Xuyên không',
    description:
      'Một thiên tài bị dời đến thời cổ, nơi mọi quyết định đều ảnh hưởng đến các huyết mạch và vận mệnh của cả thế giới.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #16a34a 35%, #86efac 100%)',
    views: '458K',
    rating: 4.5,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Khởi nguyên', duration: '10:34', isVip: false },
      { id: 2, title: 'Chương 2: Nước biển', duration: '13:12', isVip: false },
      { id: 3, title: 'Chương 3: Long rồng', duration: '14:50', isVip: false },
      { id: 4, title: 'Chương 4: Đáy biển', duration: '15:31', isVip: true },
      { id: 5, title: 'Chương 5: Sứ giả', duration: '16:12', isVip: true },
    ],
  },
  {
    id: 'thien-nhan-trong-qua-khu',
    title: 'Thiên Nhân Trong Quá Khứ',
    author: 'Sương Gió',
    category: 'Đô thị',
    description:
      'Một người đàn ông sống trong quá khứ bắt đầu chạm vào tương lai của chính mình từ những ký ức không thuộc về mình.',
    cover: 'linear-gradient(135deg, #4c1d95 0%, #ec4899 35%, #fbcfe8 100%)',
    views: '431K',
    rating: 4.2,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Mục tiêu', duration: '11:10', isVip: false },
      { id: 2, title: 'Chương 2: Quá khứ', duration: '12:56', isVip: false },
      { id: 3, title: 'Chương 3: Gió lớn', duration: '13:32', isVip: false },
      { id: 4, title: 'Chương 4: Vết thương', duration: '15:08', isVip: true },
      { id: 5, title: 'Chương 5: Lời hứa', duration: '14:40', isVip: true },
    ],
  },
  {
    id: 'huyen-anh-bang-hong',
    title: 'Huyền Ảnh Băng Hồng',
    author: 'Hoa Đậu',
    category: 'Ngôn tình',
    description:
      'Một mối tình bắt đầu bằng lời nguyền, rồi dần phát triển thành một chặng đường không thể quay đầu.',
    cover: 'linear-gradient(135deg, #4c0519 0%, #be185d 35%, #f9a8d4 100%)',
    views: '504K',
    rating: 4.7,
    isVip: false,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Nửa đêm', duration: '11:45', isVip: false },
      { id: 2, title: 'Chương 2: Hồng băng', duration: '12:56', isVip: false },
      { id: 3, title: 'Chương 3: Đêm lạnh', duration: '13:18', isVip: true },
      { id: 4, title: 'Chương 4: Từ từ', duration: '14:02', isVip: false },
      { id: 5, title: 'Chương 5: Nơi ở', duration: '12:09', isVip: false },
    ],
  },
  {
    id: 'tam-an-ly-tranh',
    title: 'Tâm Ẩn Lý Tranh',
    author: 'Bích Lam',
    category: 'Trinh thám',
    description:
      'Mỗi nghi ngờ đều tiếp tục mở ra không gian sâu kín, khiến cả thành phố dần nhầm lẫn giữa đúng và sai.',
    cover: 'linear-gradient(135deg, #0f172a 0%, #1f2937 35%, #fca5a5 100%)',
    views: '376K',
    rating: 4.3,
    isVip: true,
    status: 'Đang ra',
    episodes: [
      { id: 1, title: 'Chương 1: Mồi câu', duration: '12:03', isVip: false },
      { id: 2, title: 'Chương 2: Vết cắt', duration: '13:46', isVip: false },
      { id: 3, title: 'Chương 3: Ranh giới', duration: '15:05', isVip: true },
      { id: 4, title: 'Chương 4: Hồi âm', duration: '14:20', isVip: true },
      { id: 5, title: 'Chương 5: Góc tối', duration: '16:18', isVip: true },
    ],
  },
  {
    id: 'thien-dia-bat-kyet',
    title: 'Thiên Địa Bất Kỵ',
    author: 'Đông Lý',
    category: 'Fantasy',
    description:
      'Một thiên giới sụp đổ để nhường chỗ cho thế hệ trẻ biết cách xây dựng lại thứ mà họ tin là quyền lực.',
    cover: 'linear-gradient(135deg, #022c22 0%, #0f766e 35%, #5eead4 100%)',
    views: '489K',
    rating: 4.4,
    isVip: false,
    status: 'Hoàn thành',
    episodes: [
      { id: 1, title: 'Chương 1: Tái sinh', duration: '11:52', isVip: false },
      { id: 2, title: 'Chương 2: Huyền môn', duration: '12:29', isVip: false },
      { id: 3, title: 'Chương 3: Bất khả', duration: '14:18', isVip: false },
      { id: 4, title: 'Chương 4: Vách trời', duration: '15:43', isVip: true },
      { id: 5, title: 'Chương 5: Rầm', duration: '13:59', isVip: true },
    ],
  },
]

export const genres = [
  { name: 'Tiên hiệp', stories: 128 },
  { name: 'Kiếm hiệp', stories: 94 },
  { name: 'Huyền huyễn', stories: 112 },
  { name: 'Ngôn tình', stories: 142 },
  { name: 'Đô thị', stories: 66 },
  { name: 'Trinh thám', stories: 53 },
  { name: 'Kinh dị', stories: 41 },
  { name: 'Xuyên không', stories: 75 },
  { name: 'Lịch sử', stories: 49 },
  { name: 'Fantasy', stories: 89 },
  { name: 'Cổ đại', stories: 57 },
  { name: 'Võng du', stories: 61 },
]

export const stats = {
  totalStories: 320,
  listeners: '2.4M',
  vipMembers: '184K',
}

export const rankingTabs = ['Tuần', 'Tháng', 'Tất cả']

export const navItems = [
  { label: 'Trang chủ', path: '/' },
  { label: 'Thư viện', path: '/library' },
  { label: 'Thể loại', path: '/genres' },
  { label: 'Xếp hạng', path: '/rankings' },
  { label: 'VIP', path: '/subscription' },
]
